### ISSUE TITLE
Error viewing other revisions in details viewer if the query ends with whitespace

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/yangcatalog-ui#10]
If the query in the details viewer ends with whitespace after a correct module name, the details for the module will successfully be shown. However, when a different revision is selected, an error occurs.
Steps to replicate:
1. on the module details page enter `ietf-yang-types ` (including the trailing whitespace) into the search box
2. click on the revision box and select any other revision
3. you will get an error message something along the lines of
```
Http failure response for https://yangcatalog.org/api/yang-search/v2/module-details/ietf-yang-types%20@2021-04-14: 400 BAD REQUEST
```

**Comment by SlavomirMazurPantheon** [comment]
Fixed by https://github.com/YangCatalog/yangcatalog-ui/commit/df47dffcd03003137733a725881d0afdb21b62c6.
