### ISSUE TITLE
List of platform/OS version for a YANG module

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#100]
Through the web UI and the API, for a set of YANG modules, display a table of vendor/platform/OS version supporting these modules based on the meta data.

From the module detail page, there should be a way to jump to the above list via a button/icon near the "tree view" / "impact analysis" ones (of course for just this module).

**Comment by SlavomirMazurPantheon** [comment]
Hello @evyncke,

I just deployed first changes related to this issue to the PROD:
- You can find them in [module details](https://yangcatalog.org/yang-search/module_details) for example see https://yangcatalog.org/yang-search/module_details/huawei-aaa
- There is a clickable `Implementations` next to the `Impact analysis` - modal window is opened on click with list of implementations for particular module
- In modal window, you can click on platform (hyperlink) which will take you to the YANG Implementation overview - example: https://yangcatalog.org/yang-search/implementations?vendor=huawei&platform=atn-980b
- Software versions for this platform will be listed here and also list of the modules

Please, let me know if there is something that you want to add/remove update as this is completely new functionality and might need to be adjusted.

Regards,
Slavomír Mazúr

**Comment by evyncke** [comment]
Really cool indeed !

Just perhaps an improvement, e.g., in [Cisco ISR4K](https://yangcatalog.org/yang-search/implementations?vendor=cisco&platform=ISR4000) I only see the oldest SW version, it would be really useful to be able to click on any software version to have the related view.

Thank you anyway !

Regards

**Comment by SlavomirMazurPantheon** [comment]
Hello,
software versions are now sorted alphabetically and "selected" software version name is also part of the title.
It is possible to click on the name of the software version on overview table to display modules - table is then updated, modules are loaded.
I added NOTE paragraph for this so user know how to switch between SW versions.

Regards
