### ISSUE TITLE
conflicts between automated compilation vs manual validation

### ISSUE THREAD

**Issue by boucadair** [YangCatalog/yangcatalog-ui#29]
When checking https://datatracker.ietf.org/doc/draft-ietf-opsawg-l2nm/, I see that the yangcatalog entry is an old one. I think there is something to be fixed at the datatracker. 

When accessing directlty https://yangcatalog.org/yang-search/module_details/ietf-l2vpn-ntw, I see that the lestest version of the draft is not cited under "reference".

In addition, the compilation results indicate an error with yangdump-pro: https://yangcatalog.org/results/ietf-l2vpn-ntw@2021-10-01_ietf.html. However, when compiling the module using https://yangcatalog.org/yangvalidator, we got the following: 

```
Yangdump-pro Validation

No warnings or errors
```

**Comment by SlavomirMazurPantheon** [comment]
Hello,

thanks for pointing out this issue. It was a UI bug, where we had the validation result available - it was in the payload, but was not displayed in the compilation results.
Feel free to check it.

Regards,
Slavomir Mazur
