### ISSUE TITLE
Need basic help for impact analysis

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#3]
The mouse moves modify the presentation: this is nice of course but a help button/text would help beginners.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

by mouse moves you mean those when you hover over checkboxes at the left side - which means that we could add some kind of tooltip when you hover over specific maturity level or direction?

Or add little question mark icon after Organizations, Maturity, Direction label which after click/hover will display short description of what is Maturity, Direction ...

**Comment by evyncke** [comment]
No more about the interactions with the ‘graphical part’

From: SlavomirMazurPantheon ***@***.***>
Reply-To: YangCatalog/yangcatalog-ui ***@***.***>
Date: Wednesday, 14 July 2021 at 08:38
To: YangCatalog/yangcatalog-ui ***@***.***>
Cc: Eric Vyncke ***@***.***>, Author ***@***.***>
Subject: Re: [YangCatalog/yangcatalog-ui] Need basic help for impact analysis (#3)


Hello,

by mouse moves you mean those when you hover over checkboxes at the left side - which means that we could add some kind of tooltip when you hover over specific maturity level or direction?

Or add little question mark icon after Organizations, Maturity, Direction label which after click/hover will display short description of what is Maturity, Direction ...

**Comment by SlavomirMazurPantheon** [comment]
We are able to use alert component which is widely used in the new UI.

If you open this URL: https://yangcatalog.org/yang-search/impact_analysis/random
You will see red rectangle containing information about failure.

We can place information into this alert - it will have blue color and some text. 
It can be displayed for certain amount of time (then disappears) or it can be displayed after clicking on some question mark icon maybe?
Do you think it will be sufficient enough?

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I just added new commit fba00db7e55934f8aa3179332c6be5c4b55b5df0 which adds instructions with the following text:
```
INFO: Use scroll to zoom in/out the topology. Click on the node to display details. Drag and move nodes to change the topology.
```
After a discussion with @miroslavKovacPantheon, we did not place the instructions in the alert component as I proposed, but only as text, which is located just above the topology/graph.

Regards,
Slavomir Mazur
