### ISSUE TITLE
Query the YANG catalog =>Difficult to find the information

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/yangcatalog-ui#32]
Hi,

When receiving questions on how to query the yangcatalog, I realize that this information is completely hidden, under a "contribute" section.
https://yangcatalog.org/contribute.html
=> Download a YANG Catalog postman collection here to explore the API with examples.

At the very minimum, this information should be under https://yangcatalog.org/use.html. Btw, "use" is more "use cases".
A better solution: a new tab called "Query", which would contain the following information;

Download a YANG Catalog postman collection here to explore the API with examples, based on this YANG module.

This method will work for any node within the yang-catalog:
    +--rw catalog
       +--rw modules
       |  +--rw module* [name revision organization]
       |     +--rw name                     yang:yang-identifier
       |     +--rw revision                 union
       |     +--rw organization             string
       |     +--rw ietf
       |     |  +--rw ietf-wg?   string
       |     +--rw namespace                inet:uri
       |     +--rw schema?                  inet:uri
       |     +--rw generated-from?          enumeration
       |     +--rw maturity-level?          enumeration
       |     +--rw document-name?           string
       |     +--rw author-email?            yc:email-address
       |     +--rw reference?               inet:uri
       |     +--rw module-classification    enumeration
       |     +--rw compilation-status?      enumeration
       |     +--rw compilation-result?      inet:uri
       |     +--rw prefix?                  string
       |     +--rw yang-version?            enumeration
       |     +--rw description?             string
       |     +--rw contact?                 string
       |     +--rw module-type?             enumeration
       |     +--rw belongs-to?              yang:yang-identifier
       |     +--rw tree-type?               enumeration
       |     +--rw submodule* [name revision]
       |     |  +--rw name        yang:yang-identifier
       |     |  +--rw revision    union
       |     |  +--rw schema?     inet:uri
       |     +--rw dependencies* [name]
       |     |  +--rw name        yang:yang-identifier
       |     |  +--rw revision?   union
       |     |  +--rw schema?     inet:uri
       |     +--rw dependents* [name]
       |     |  +--rw name        yang:yang-identifier
       |     |  +--rw revision?   union
       |     |  +--rw schema?     inet:uri
       |     +--rw semantic-version?           yc:semver
       |     +--rw derived-semantic-version?   yc:semver
       |     +--rw implementations
       |        +--rw implementation* [vendor platform software-version software-flavor]
       |           +--rw vendor              string
       |           +--rw platform            string
       |           +--rw software-version    string
       |           +--rw software-flavor     string
       |           +--rw os-version?         string
       |           +--rw feature-set?        string
       |           +--rw os-type?            string
       |           +--rw feature*            yang:yang-identifier
       |           +--rw deviation* [name revision]
       |           |  +--rw name        yang:yang-identifier
       |           |  +--rw revision    union
       |           +--rw conformance-type?   enumeration
       +--rw vendors
          +--rw vendor* [name]
             +--rw name         string
             +--rw platforms
                +--rw platform* [name]
                   +--rw name                 string
                   +--rw software-versions
                      +--rw software-version* [name]
                         +--rw name                string
                         +--rw software-flavors
                            +--rw software-flavor* [name]
                               +--rw name         string
                               +--rw protocols
                               |  +--rw protocol* [name]
                               |     +--rw name                identityref
                               |     +--rw protocol-version*   string
                               |     +--rw capabilities*       string
                               +--rw modules
                                  +--rw module* [name revision organization]
                                     +--rw name                -> /catalog/modules/module/name
                                     +--rw revision            -> /catalog/modules/module/revision
                                     +--rw organization        -> /catalog/modules/module/organization
                                     +--rw os-version?         string
                                     +--rw feature-set?        string
                                     +--rw os-type?            string
                                     +--rw feature*            yang:yang-identifier
                                     +--rw deviation* [name revision]
                                     |  +--rw name        yang:yang-identifier
                                     |  +--rw revision    union
                                     +--rw conformance-type?   enumeration

**Comment by SlavomirMazurPantheon** [comment]
Following changes were made in https://github.com/YangCatalog/yangcatalog-ui/pull/33:
- new tab added: **Query**
- **Use** tab renamed to **Use cases**
- Postman collection download Info moved from **Contribute** to **Query** tab
- Description of yang-catalog node moved from **Use cases** to **Query** tab
