### ISSUE TITLE
Basic checks on new user request

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#36]
When a user wants to register to the YC.O API, let's do back checks:

1. use a regex to check the email address (or any other mechanism)
2. minimum length in the explanations
3. non-empty username, names
4. check that username is not already in use

**Comment by SlavomirMazurPantheon** [comment]
Hello,

following changes were made in PR #37:
    - email field validation added
    - minimum length of 25 characters for motivation field
    - space (or multiple spaces) is no longer valid value for any filed
    - checking if username is not already in use
