### ISSUE TITLE
Unique and persistent URI for all nodes/leaves

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#43]
From the tree view (and everywhere when a leaf/node is displayed), there must be a persistent and unique URI for this leaf/node, which will display the YANG module part related to this node/leaf. The URI will include the module name + revision + the path the the leaf/node.

For example, in https://yangcatalog.org/yang-search/yang_tree/openconfig-bgp@2021-06-16 followed by /oc-rib-bgp:bgp-rib?container/oc-rib-bgp:afi-safis?container/oc-rib-bgp:afi-safi?list/oc-rib-bgp:ipv6-srte-policy?container/oc-rib-bgp:neighbors?container (of course, the URI must be URL compatible).

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I made some changes to the existing UI.
It is possible to see YANG tree here: https://yangcatalog.org/yang-search/yang_tree/yang-catalog@2018-04-03

I added "?" icon next to node name - after click modal window is displayed with corresponding YANG module part.
After clicking on leaf icon same modal window is displayed (this was also working in the past).
Also URL is changed when modal window is opened, so you are able to copy it and send to someone else.
Structure of URL is: https://yangcatalog.org/yang-search/show_node/:node/:path/:revision
Example:
https://yangcatalog.org/yang-search/show_node/yang-catalog/%2Fyc%3Acatalog%3Fcontainer%2Fyc%3Amodules%3Fcontainer%2Fyc%3Amodule%3Flist/2018-04-03

Please feel free to test it and let me know if something needs to be added / changed.

Regards,
Slavomir Mazur
