### ISSUE TITLE
Using IETF Matomo analytics

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#52]
The main pages but also the search, validator, ... pages (and in a 2nd step the API) must use the Matomo interface to the IETF analytics engine.

@rjsparks will provide the lines of Javascript to insert in all served HTML pages. I am starting an email thread on this topic.

**Comment by evyncke** [comment]
@rjsparks has sent by email the javascript code to be insert in all static/dynamic pages.

**Comment by SlavomirMazurPantheon** [comment]
Hello @evyncke,

Matomo code snipped was added and now it is also deployed in PROD.
Please let me know, if the data is being sent to the IETF analytics engine.

Regards,
Slavomir Mazur

**Comment by evyncke** [comment]
It seems to work fine indeed on all the pages (except probably for the API ones).

@rjsparks can you confirm that the data is indeed accepted and validated by Matomo ?

**Comment by rjsparks** [comment]
Yes, the matomo engine is ingesting data from yangcatalog. Greg and I are discussing how to make reports available.
