### ISSUE TITLE
Add header link to enable preloading

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/yangcatalog-ui#57]
After enabling [HTTP/2 PUSH functionality](https://github.com/YangCatalog/deployment/issues/114), link headers should be added to the certain resources (images, stylesheets, scripts ... ) to enable preloading.
If there is and Link header with `rel=preload` resources are pushed immediately.

**Comment by evyncke** [comment]
I am afraid that the HTTP/2 link preload does not work again. Not even for the static image :-(

**Comment by SlavomirMazurPantheon** [comment]
Hello @evyncke,

I was able to make some other improvements to the page loading.
First, fonts are now using preload functionality too.

Second, In Angular I used functionality called "lazy-loading", which reduced the size of main.js file from 3MB down to 1.7MB and reduced loading time.
Lazy-loading means that modules are loaded only when used needed. 

**Example:**
Imagine that YANG Search page is one of Angular modules. In main.js there is now only information what module should be loaded (previously, entire module was stored here). This module will be loaded only after accessing YANG Search module. This significantly reduces size of main.js file.

Preloading should work correctly, however it is something slightly different from pushing so we cannot see Push / Other in the Initiator column.
On the other side, some assets (images, fonts) are requested BEFORE HTML file has been parsed completely.
Very good comparison can be found [here](https://www.keycdn.com/blog/http-preload-vs-http2-push).

Regards,
Slavomír Mazúr

**Comment by evyncke** [comment]
Good idea to preload *external* ressources as in this case 'HTTP/2 push' is not possible.

Good as well for the lazy load.

***BUT***, there are local ressources (css, logo) that would benefit from a HTTP/2 push (i.e., in the HTTP header outside of the HTML head/body) and they are not pushed.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

I finally found out how to setup PUSH for certain pages in NGINX config file.
Multiple resources are now pushed using HTTP/2 PUSH:
- ietf-logo.svg (used on each page in the footer)
- yang-catalog-header.png (home.html)
- two other .jpg images in use.html
- styles.css file
