### ISSUE TITLE
All pages have the same title

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#60]
It appears that all YC.O pages have the same <title>YANG Catalog</title>.

This is causing problems in the Matomo analytics are pages are also differentiated by their HTML title tag.

=> need to use "YANG Search", "YANG Module Viewer", ... HTML tag on all pages.

**Comment by SlavomirMazurPantheon** [comment]
Hello @evyncke, 

titles are now unique on each page - usually contains name of the page itself (Home, About, YANG Search ...).
Please, feel free to check it on yangcatalog.org and let me know whether any further changes should be made.

To the future it is possible to add "more information" to the title if it's something Matomo will benefit from. 
For example in YANG Validator, we can add number of validated RFC document if user decide to validate RFC by its number or searched term in YANG Search ...

Regards,
Slavomír Mazúr

**Comment by evyncke** [comment]
Superb !

No real need to get additional information, with your changes it is perfectly fine.

Thank you

-éric
