### ISSUE TITLE
HTML title not always set

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/yangcatalog-ui#65]
It seems that either HTML titles are not set on all the pages or that Matomo script is unable to extract them.

See attached email where there are 890 pages where "page name not defined" and this the largest category. Alas no more information added by Matomo...
[Untitled.pdf](https://github.com/YangCatalog/yangcatalog-ui/files/8551896/Untitled.pdf)

**Comment by SlavomirMazurPantheon** [comment]
Hello @evyncke,

I checked every page and it seems that the title is set correctly everywhere.

However, Average time on page is 0:00, also exit rate 0% which is suspicious.
At this page: https://matomo.org/faq/general/faq_75/ see paragraph 3)
I added this HTTPS to the Matomo server URL (see PR above), so this might help. I applied these changes on PROD.
Please let me know next week, whether this was resolved. If not, I will investigate further.

P.S: Is there any chance that I could also be added to the mailing list and receive this Matomo weekly report?

Regards,
Slavomir Mazur

**Comment by evyncke** [comment]
The change to HTTPS may indeed do the trick, wait and see.

To which email should I request the report to be sent ? (please send the email over email ;-) or tell me whether it is your Pantheon email)

**Comment by SlavomirMazurPantheon** [comment]
My Pantheon email please :)

**Comment by evyncke** [comment]
Thank you !
